captcha-enabled: false
slots:
  music: 0
  players: 8
  whitelist: 6
items:
  music: JUKEBOX
  players:
    visible: ENDER_EYE
    hidden: SLIME_BALL
  whitelist:
    enabled: BLACK_STAINED_GLASS_PANE
    disabled: WHITE_STAINED_GLASS_PANE
scoreboard:
  title: "§e§lDragon§6§lCraft"
  prefix: "§e» "
  nick: "§6Nick: §e"
  ping: "§6Ping: §e"
  rank: "§6Ranga: §e"
  time: "§6Godzina: §e"
  server-ip: "  §e» §6§lDCRFT.PL §e«"
  server:
    all: "§6Gracze ogółem: §e"
disabled_default_permission: "cb.adm"